### ISSUE TITLE
Error in INSTALL.md?

### ISSUE THREAD

**Issue by williamhobbs** [pencleanenergy/MATCH-model#63]
I think there might be a typo/error in: https://github.com/pencleanenergy/MATCH-model/blob/712f35031c9e06b2b8cb1a162bb5d93bbc16ad11/INSTALL.md?plain=1#L42-L48:

I expected the last line to be something like `jupyter notebook` instead of a repeat of the installation command.

**Comment by grgmiller** [comment]
Thanks for flagging this - this does appear to be a typo. 

I think that the instructions should actually read:
```
conda install jupyter
jupyter notebook
```

If you notice any other issues while setting up the model, please let us know!

**Comment by williamhobbs** [comment]
Glad to help! I've just posted two other issues with items that might be helpful.
