### ISSUE TITLE
Error happen during demonstrating.

### ISSUE THREAD

**Issue by jieyao-MilestoneHub** [pencleanenergy/MATCH-model#72]
Hello authors! Thank you for your valuable contributions to this topic. I would like to start by demonstrating the well-tuned model you've provided. Should I begin by running the run_scenario.ipynb as the first step?

If so, I'd like to inquire about the error in the screenshot. I've only set my path, and I haven't made any other changes to the code. My environment is as follows: Anaconda with Python 3.10. Could you please advise if there's a need to set an API_KEY somewhere, or if any necessary steps should be taken before running this file? Your guidance would be greatly appreciated!

![Q01](https://github.com/pencleanenergy/MATCH-model/assets/60685621/153a2126-0f60-4e0d-bc5f-164b7a4d9190)
![Q02](https://github.com/pencleanenergy/MATCH-model/assets/60685621/21dd4fcf-7a85-4140-9e15-44fe56fb6671)
![Q03](https://github.com/pencleanenergy/MATCH-model/assets/60685621/2c62d1cb-1914-4318-9c1e-c7f364407b66)
![Q04](https://github.com/pencleanenergy/MATCH-model/assets/60685621/40bfd659-31d0-40d5-a344-197a6b1c37e2)

ChienYao

**Comment by grgmiller** [comment]
Hi Chien, 

It appears that this may be happening when trying to download data from NREL, for which you need an API key. 
You can sign up for an NREL API key here: https://developer.nrel.gov/signup/
Once you have that, you need to enter your email and API key in the "general" tab of the `model_inputs` spreadsheet

Let me know if this fixes your issue!

**Comment by jieyao-MilestoneHub** [comment]
Hello grgmiller, thank you for your detailed explanation!
